# Generated by Django 3.2.4 on 2021-07-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='img/%y')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='home',
            name='text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hometext',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
